# Generated by Django 4.0.4 on 2022-04-30 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название принтера')),
                ('api_key', models.CharField(max_length=255, verbose_name='Ключ доступа к API')),
                ('point_id', models.CharField(max_length=255, verbose_name='Точка к которой привязан принтер')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтера',
                'db_table': 'printer',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, verbose_name='Тип чека')),
                ('order', models.JSONField()),
                ('status', models.CharField(max_length=255, verbose_name='Статус чека')),
                ('printer_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='check.printer')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'check',
            },
        ),
    ]
