# Generated by Django 4.0.4 on 2022-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='type',
        ),
        migrations.AddField(
            model_name='check',
            name='type_check',
            field=models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='kitchen', max_length=255, verbose_name='Тип чека'),
        ),
        migrations.AddField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default=1, max_length=255, verbose_name='Тип чека'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('rendered', 'Оказаный'), ('printed', 'Распечатаный')], default='new', max_length=255, verbose_name='Статус чека'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='point_id',
            field=models.IntegerField(default=0, verbose_name='Точка к которой привязан принтер'),
        ),
    ]
